# Generated by Django 6.0 on 2025-12-07 07:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_category_dispute_emaillog_invoice_job_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", api.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="commission_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="job",
            name="provider_earnings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
