# Generated by Django 6.0 on 2025-12-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_systemsettings_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("open_for_bids", "Open for Bids"),
                    ("analyzing", "Analyzing"),
                    ("matched", "Matched"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
