# Generated by Django 6.0 on 2025-12-30 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Cached username in case user is deleted",
                        max_length=150,
                    ),
                ),
                ("user_role", models.CharField(blank=True, max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("status_change", "Status Change"),
                            ("bid_action", "Bid Action"),
                            ("payment", "Payment"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(help_text="Model that was changed", max_length=50),
                ),
                ("object_id", models.IntegerField(blank=True, null=True)),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of object",
                        max_length=200,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(default=dict, help_text="Before/after values"),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="audit_logs_timesta_e93820_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="audit_logs_user_id_e11c73_idx",
                    ),
                    models.Index(
                        fields=["model_name", "-timestamp"],
                        name="audit_logs_model_n_f15e9d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "proposal",
                    models.TextField(
                        help_text="Provider's proposal explaining why they're best for the job"
                    ),
                ),
                (
                    "estimated_duration",
                    models.CharField(
                        help_text="e.g., '2 hours', '1 day', '3-5 days'", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="api.provider",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="api.request",
                    ),
                ),
            ],
            options={
                "db_table": "bids",
                "ordering": ["amount", "-created_at"],
                "unique_together": {("request", "provider")},
            },
        ),
    ]
