# Generated by Django 6.0 on 2025-12-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_category_image_auditlog_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="experience_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="provider",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("under_review", "Under Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="completed_jobs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="provider",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
