# Generated by Django 6.0 on 2025-12-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_provider_bio_provider_experience_years_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemsettings",
            name="created_at",
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="contact_email",
            field=models.EmailField(default="support@serveflow.ai", max_length=254),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="currency_symbol",
            field=models.CharField(default="$", max_length=10),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="enable_ai_analysis",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="enable_bidding_system",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="maintenance_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="min_payout_amount",
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="platform_name",
            field=models.CharField(default="ServeFlow AI", max_length=100),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="require_provider_verification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_host",
            field=models.CharField(default="smtp.gmail.com", max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_password",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_port",
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="smtp_user",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="tax_percentage",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
