# Generated by Django 6.0 on 2026-01-01 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_systemsettings_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="gemini_api_key_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="gemini_api_key_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="gemini_api_key_3",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="gemini_api_key_4",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.job",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
    ]
