# Generated by Django 6.0 on 2026-01-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_systemsettings_gemini_api_key_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="stripe_checkout_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_mode",
            field=models.CharField(
                choices=[("test", "Test"), ("live", "Live")],
                default="test",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_public_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_secret_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="stripe_webhook_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
