# Generated by Django 6.0 on 2026-04-12 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_message_read_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="requests/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.IntegerField(default=0)),
                ("is_used", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_otps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="verif/portfolio/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_images",
                        to="api.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_description", models.TextField()),
                ("ai_title", models.CharField(blank=True, max_length=200)),
                ("severity_score", models.IntegerField(null=True)),
                ("complexity", models.CharField(blank=True, max_length=20)),
                ("urgency", models.CharField(blank=True, max_length=20)),
                (
                    "est_price_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "est_price_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("est_duration_hrs", models.FloatField(null=True)),
                ("ai_analysis_raw", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INGESTING", "Ingesting"),
                            ("OPEN", "Open"),
                            ("BIDDING", "Bidding"),
                            ("AWARDED", "Awarded"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="INGESTING",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ai_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.category",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("images", models.ManyToManyField(blank=True, to="api.requestimage")),
            ],
            options={
                "db_table": "service_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VerificationBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_front", models.ImageField(upload_to="verif/ids/")),
                ("id_back", models.ImageField(upload_to="verif/ids/")),
                ("selfie_with_id", models.ImageField(upload_to="verif/selfies/")),
                (
                    "certificate",
                    models.ImageField(blank=True, null=True, upload_to="verif/certs/"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("APPROVED", "Approved"),
                            ("CONDITIONAL", "Conditional"),
                            ("REJECTED", "Rejected"),
                            ("UNDER_REVIEW", "Under Review"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "portfolio_imgs",
                    models.ManyToManyField(blank=True, to="api.portfolioimage"),
                ),
                (
                    "provider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_bundle",
                        to="api.provider",
                    ),
                ),
            ],
            options={
                "db_table": "verification_bundles",
            },
        ),
        migrations.CreateModel(
            name="VerificationAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trust_score", models.FloatField()),
                ("id_score", models.FloatField()),
                ("liveness_score", models.FloatField()),
                ("cert_score", models.FloatField(null=True)),
                ("portfolio_score", models.FloatField(null=True)),
                ("decision", models.CharField(max_length=20)),
                ("gemini_raw", models.JSONField()),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("is_human_review", models.BooleanField(default=False)),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="api.verificationbundle",
                    ),
                ),
            ],
            options={
                "db_table": "verification_audit_logs",
            },
        ),
        migrations.CreateModel(
            name="ProviderMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_score", models.FloatField()),
                ("affinity_score", models.FloatField()),
                ("proximity_score", models.FloatField()),
                ("reputation_score", models.FloatField()),
                ("pulse_bonus", models.FloatField()),
                ("distance_km", models.FloatField()),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_matches",
                        to="api.provider",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="api.servicerequest",
                    ),
                ),
            ],
            options={
                "db_table": "provider_matches",
                "unique_together": {("request", "provider")},
            },
        ),
    ]
