# Generated by Django 6.0 on 2026-04-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_promptversion_ratecard"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="provider",
            name="skills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
