# Generated by Django 6.0 on 2026-04-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="contact_email",
            field=models.EmailField(
                blank=True, default="support@serveflow.ai", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="currency_symbol",
            field=models.CharField(blank=True, default="$", max_length=10),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="platform_name",
            field=models.CharField(blank=True, default="ServeFlow AI", max_length=100),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="smtp_host",
            field=models.CharField(
                blank=True, default="smtp.gmail.com", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="smtp_port",
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
    ]
