# Generated by Django 6.0 on 2026-04-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_populate_sendgrid_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="from_email",
            field=models.CharField(
                blank=True,
                default="ServeFlow AI <noreply@serveflow.ai>",
                max_length=255,
            ),
        ),
    ]
