version: "1.0"
services:
  - name: backend
    type: web
    build:
      dockerfile: backend/Dockerfile
      context: backend
    env:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: ${DATABASE_URL}
      - key: REDIS_URL
        value: ${REDIS_URL}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: ALLOWED_HOSTS
        value: ${ALLOWED_HOSTS}
      - key: CORS_ALLOWED_ORIGINS
        value: ${CORS_ALLOWED_ORIGINS}
    ports:
      - port: 8000
        protocol: http

  - name: frontend
    type: web
    build:
      dockerfile: frontend/Dockerfile
      context: frontend
    env:
      - key: VITE_API_URL
        value: ${VITE_API_URL}
      - key: VITE_WS_URL
        value: ${VITE_WS_URL}
    ports:
      - port: 80
        protocol: http

  - name: ai-service
    type: web
    build:
      dockerfile: ai_service/Dockerfile
      context: ai_service
    env:
      - key: GEMINI_API_KEY
        value: ${GEMINI_API_KEY}
    ports:
      - port: 8001
        protocol: http

  - name: matching-service
    type: web
    build:
      dockerfile: matching_service/Dockerfile
      context: matching_service
    ports:
      - port: 8002
        protocol: http
