"""
Django settings for serveflow project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

load_dotenv()


def env_bool(name: str, default: bool = False) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in ("true", "1", "yes", "on")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-%+%j%@=)8hhyzmg1rf_x84j4r(oa!-sr5-)ou*g6hdb9gvr^m^")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG", default=True)

def _build_allowed_hosts():
    """Parse ALLOWED_HOSTS; in DEBUG also allow this machine's LAN IP (Vite network URL)."""
    raw = os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]")
    hosts = [h.strip() for h in raw.split(",") if h.strip() and h.strip() != "*"]
    if DEBUG:
        for extra in ("backend", "host.docker.internal"):
            if extra not in hosts:
                hosts.append(extra)
        try:
            import socket
            probe = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            probe.connect(("8.8.8.8", 80))
            lan_ip = probe.getsockname()[0]
            probe.close()
            if lan_ip and lan_ip not in hosts:
                hosts.append(lan_ip)
        except OSError:
            pass
    return hosts


ALLOWED_HOSTS = _build_allowed_hosts()
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")
# When True and Stripe is configured, manual/auto publishes require Checkout before jobs are created.
# Set ESCROW_ON_PUBLISH=true in production when Stripe is configured (manual/auto publish require Checkout).
ESCROW_ON_PUBLISH = os.environ.get("ESCROW_ON_PUBLISH", "False").lower() == "true"
AI_SERVICE_URL = os.environ.get("AI_SERVICE_URL", "http://localhost:8001")
AI_SERVICE_INTERNAL_TOKEN = (os.environ.get("AI_SERVICE_INTERNAL_TOKEN") or "serveflow-internal-dev").strip()
MATCHING_SERVICE_URL = os.environ.get("MATCHING_SERVICE_URL", "http://localhost:8002")

# Single Gemini key from env (also read in SystemSettings.get_gemini_api_keys for vision).
GEMINI_API_KEY = (os.environ.get("GEMINI_API_KEY") or "").strip()

# AI image vision (Gemini); AIImageAnalysisView clamps timeout 5–40s and retries per key in code.
AI_VISION_TIMEOUT_SECONDS = float(os.environ.get("AI_VISION_TIMEOUT_SECONDS", "18"))
AI_VISION_RETRIES_PER_KEY = int(os.environ.get("AI_VISION_RETRIES_PER_KEY", "2"))
# Demo-only: returns placeholder analysis when Gemini is unavailable. Opt-in (do not silently fake AI).
AI_VISION_ALLOW_SIMULATED_FALLBACK = (
    os.environ.get("AI_VISION_ALLOW_SIMULATED_FALLBACK", "False").lower() == "true"
)



# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "channels",
    "api",
]

MIDDLEWARE = [
    "serveflow.middleware.AllowLanHostMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "serveflow.middleware.DisableCSRFForAPIMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "serveflow.middleware.SecurityHeadersMiddleware",
    "serveflow.middleware_upload.UploadTooLargeMiddleware",
]

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Production Security
ENABLE_SSL = os.environ.get("ENABLE_SSL", "False").lower() == "true"
_ssl_redirect_env = os.environ.get("SECURE_SSL_REDIRECT", "").lower()
if _ssl_redirect_env == "true":
    _use_ssl_redirect = True
elif _ssl_redirect_env == "false":
    _use_ssl_redirect = False
else:
    _use_ssl_redirect = ENABLE_SSL or not DEBUG
if _use_ssl_redirect:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000 # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

ROOT_URLCONF = "serveflow.urls"

# Integrate React frontend build with Django static serving
import os
FRONTEND_DIST = BASE_DIR / 'frontend_dist'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [FRONTEND_DIST] if os.path.exists(FRONTEND_DIST) else [],

        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "serveflow.asgi.application"

# Channels configuration
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# PostgreSQL everywhere (Docker Compose, local dev, production). Override via DATABASE_URL.
_DEFAULT_DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgres://postgres:postgres@localhost:5432/serveflow",
)
DATABASES = {
    "default": dj_database_url.config(
        default=_DEFAULT_DATABASE_URL,
        conn_max_age=600,
    )
}

# SSL is required for managed PostgreSQL; disable for local/Docker via DATABASE_SSLMODE=disable
if not DEBUG and "postgresql" in DATABASES["default"]["ENGINE"]:
    sslmode = os.environ.get('DATABASE_SSLMODE', 'require')
    if sslmode:
        DATABASES['default']['OPTIONS'] = {'sslmode': sslmode}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

if os.path.exists(FRONTEND_DIST):
    STATICFILES_DIRS = [FRONTEND_DIST]


# Media files (uploads) — align with frontend/nginx client_max_body_size (10MB)
UPLOAD_MAX_BYTES = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = UPLOAD_MAX_BYTES
FILE_UPLOAD_MAX_MEMORY_SIZE = UPLOAD_MAX_BYTES
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email Configuration
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'ServeFlow AI <noreply@serveflow.ai>')

# Process env only; DB credentials from credentials.txt are applied at send time (see api.emails).
if EMAIL_HOST_USER:
    EMAIL_BACKEND = os.environ.get(
        "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
    )
else:
    EMAIL_BACKEND = os.environ.get(
        "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
    )

# --- ServeFlow v2.0 OTP & Security Settings ---
ENABLE_EMAIL_OTP = env_bool('ENABLE_EMAIL_OTP', default=True)

OTP_EXPIRY_SECONDS = int(os.environ.get('OTP_EXPIRY_SECONDS', 600))
OTP_MAX_ATTEMPTS = int(os.environ.get('OTP_MAX_ATTEMPTS', 5))
OTP_RATE_LIMIT_PER_HOUR = int(os.environ.get('OTP_RATE_LIMIT_PER_HOUR', 3))

# Auth abuse protection (lockouts use cache; Redis when REDIS_URL is set)
AUTH_LOCKOUT_MAX_ATTEMPTS = int(os.environ.get('AUTH_LOCKOUT_MAX_ATTEMPTS', 5))
AUTH_LOCKOUT_WINDOW_SECONDS = int(os.environ.get('AUTH_LOCKOUT_WINDOW_SECONDS', 900))
AUTH_LOCKOUT_DURATION_SECONDS = int(os.environ.get('AUTH_LOCKOUT_DURATION_SECONDS', 900))
AUTH_MAX_BODY_BYTES = int(os.environ.get('AUTH_MAX_BODY_BYTES', 8192))
AUTH_MAX_PASSWORD_LENGTH = int(os.environ.get('AUTH_MAX_PASSWORD_LENGTH', 128))

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'api.User'

CORS_ALLOWED_ORIGINS = os.environ.get(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://localhost:3000"
).split(",")

# Add logic to allow any local origin in development if needed, 
# but for now, we'll suggest adding specific IPs or using a wildcard if CORS_ALLOW_ALL_ORIGINS is True.
# Actually, let's just use CORS_ALLOW_ALL_ORIGINS = DEBUG for simplicity in dev.
CORS_ALLOW_ALL_ORIGINS = DEBUG

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.hf\.space$",
    r"^https://.*\.koyeb\.app$",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-request-id",
]

CSRF_TRUSTED_ORIGINS = [
    "https://serveflowai-serveflowai.hf.space",
    "https://*.hf.space",
    "https://*.koyeb.app",
    "http://localhost",
    "http://localhost:5173",
    "http://localhost:8000",
    "http://127.0.0.1",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8000",
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'auth_login': os.environ.get('RATE_AUTH_LOGIN', '10/min'),
        'auth_otp': os.environ.get('RATE_AUTH_OTP', '5/hour'),
        'auth_otp_email': os.environ.get('RATE_AUTH_OTP_EMAIL', '3/hour'),
        'auth_otp_verify': os.environ.get('RATE_AUTH_OTP_VERIFY', '20/hour'),
        'auth_register': os.environ.get('RATE_AUTH_REGISTER', '10/hour'),
        'auth_password_reset': os.environ.get('RATE_AUTH_PASSWORD_RESET', '5/hour'),
    },
}

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'serveflow-auth',
        }
    }

# --- Celery Configuration ---
# Docker/production: use Redis broker; local without Redis: run tasks inline.
if REDIS_URL:
    CELERY_BROKER_URL = REDIS_URL
    CELERY_RESULT_BACKEND = REDIS_URL
    if os.environ.get("CELERY_TASK_ALWAYS_EAGER") is not None:
        CELERY_TASK_ALWAYS_EAGER = env_bool("CELERY_TASK_ALWAYS_EAGER")
    else:
        # Docker dev stack has no celery worker — run OTP/mail tasks in-process.
        CELERY_TASK_ALWAYS_EAGER = DEBUG
else:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"
CELERY_TASK_EAGER_PROPAGATES = True
# ----------------------------

# --- Deprecated console default (managed by logic above) ---
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
